FROM node

RUN mkdir /code
WORKDIR /code

# Copy only UI files first for caching efficiency
COPY socialhome/ui/package*.json ./

# Install dependencies early to leverage Docker cache
RUN npm install

# Copy the rest of the UI code
COPY socialhome/ui/ ./

# Copy the dev entrypoint
COPY docker/dev/docker-entrypoint.sh.ui ./docker-entrypoint.sh

# Ensure entrypoint is executable
RUN chmod +x ./docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["dev"]
