version: '3'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=socialhome
      - POSTGRES_PASSWORD=socialhome
      - POSTGRES_DB=socialhome

  redis:
    image: redis
    volumes:
      - redis_data:/data

  npm:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.npm
    volumes:
      - ./socialhome:/code/socialhome

  django:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.django
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgres://socialhome:socialhome@postgres:5432/socialhome
      - DEBUG=True
      - DJANGO_SECRET_KEY=ForDevelopmentEyesOnly
    volumes:
      - ./socialhome:/code/socialhome
      - ./socialhome/ui/dist/index.html:/code/socialhome/templates/index.html:ro
    ports:
      - 8000:8000

  # Nginx for serving UI static assets
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./docker/dev/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./socialhome/ui/dist:/var/www/socialhome-ui:ro
    depends_on:
      - django

volumes:
  pg_data: {}
  pg_backups: {}
  redis_data: {}
